title: Traneh Askarzadeh
logo: /assetsimg/headshot_circle.png
#description: Seasoned transportation data scientist with a big data analysis certificate, boasting more than a decade of academic research experience. Skilled in leveraging over two years of hands-on machine learning and statistical analysis to solve real-world challenges, effectively transforming complex datasets into actionable insights for strategic decision-making in a variety of projects.
show_downloads: False
theme: jekyll-theme-minimal
