title: Taraneh Askarzadeh
logo: /assets/img/headshot_circle.png
description: >
  <strong>(703) 624-9929</strong> | 
  <a href='mailto:Taraneh.Askarzadeh@ndsu.edu'>Taraneh.Askarzadeh@ndsu.edu</a>
  <a href='https://linkedin.com/in/taraneh-askarzadeh-ph-d-b974a4b3'>
    <img src='https://img.shields.io/badge/-LinkedIn-blue?style=flat&logo=LinkedIn&logoColor=white'>
  </a>
  <a href='https://github.com/TaranehAskarzadeh'>
    <img src='https://img.shields.io/badge/-GitHub-black?style=flat&logo=GitHub&logoColor=white'>
  </a>
show_downloads: false
theme: jekyll-theme-leap day

