title: Traneh Askarzadeh
logo: /assets/img/headshot_circle.png
description: 📱 (703) 624-9929 | ✉️ [Taraneh.Askarzadeh@ndsu.edu](mailto:Taraneh.Askarzadeh@ndsu.edu)

[![LinkedIn](https://img.shields.io/badge/-LinkedIn-blue?style=flat&logo=LinkedIn&logoColor=white&link=https://linkedin.com/in/taraneh-askarzadeh-ph-d-b974a4b3)](https://linkedin.com/in/taraneh-askarzadeh-ph-d-b974a4b3)
[![GitHub](https://img.shields.io/badge/-GitHub-black?style=flat&logo=GitHub&logoColor=white&link=https://github.com/TaranehAskarzadeh)](https://github.com/TaranehAskarzadeh) 

Seasoned transportation data scientist with a big data analysis certificate, boasting more than a decade of academic research experience. Skilled in leveraging over two years of hands-on machine learning and statistical analysis to solve real-world challenges, effectively transforming complex datasets into actionable insights for strategic decision-making in a variety of projects.
show_downloads: False
theme: jekyll-theme-minimal
